[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[etherscan]
api_key = { key = "31WK7NV8HJH7PJIW5Z7EXPMVUMX5GEF3BK", chain = 10 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
